version: 0.2

phases:
  install:
    commands:
      - echo "Préparation du projet PHP Club"
  build:
    commands:
      - echo "Post-build phase - preparing artifact"
      # On crée un zip propre de l’application
      - zip -r club.zip .


artifacts:
  files:
     - club.zip
