version: 0.2

phases:
  install:
    commands:
      - echo "Préparation du projet PHP Club"
  build:
    commands:
      - echo "Post-build phase - preparing artifact"
      # On crée un zip propre de l’application
      - mkdir -p output/club
      #- zip -r output/club-app.zip . -x "output/*"
      - rsync -av --exclude='output/club/' ./ output/club/


artifacts:
  files:
    #- output/club-app.zip
     - output/club
